### ISSUE TITLE
Segmentation fault error for invalid hosts 

### ISSUE THREAD

**Issue by govindarajan** [aerospike/aerospike-client-php#102]
php -v
PHP 5.3.29 (cli) (built: May 12 2015 22:42:19) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

Aerospike client version is 3.4.8
AWS EC2 machine 

I am using aerospike client in my webserver. When I specify wrong host name in the config, it is failing with segmentation fault. In the list, even if one host is having aerspike server, then it is working fine. But when none of the server is running aerospike, it is failing.

**Comment by mikelynn2** [comment]
we've seen this as well.  if there isn't at least 1 valid server that's up, you get a seg fault

**Comment by ramynasr** [comment]
I have the issue when trying running `get()` and there are no valid servers. Looking at the coredump, it points out to line 387 here:

```
as_node_get(as_cluster* cluster, const char* ns, const uint8_t* digest, bool write, as_policy_replica replica)
{
	if (cluster->shm_info) {
		return as_shm_node_get(cluster, ns, digest, write, replica);
	}
	else {
		as_partition_table* table = as_cluster_get_partition_table(cluster, ns);
		return as_partition_table_get_node(cluster, table, digest, write, replica);
	}
}
```

That's the version I used to build my php extension:

https://github.com/aerospike/aerospike-client-c/blob/3.1.22/src/include/aerospike/as_cluster.h

backtracing the segfault

```
(gdb) bt
#0  0x00007f0bc9e46826 in as_node_get (replica=AS_POLICY_REPLICA_MASTER, write=false, digest=0x7ffe45f59ac1 "fP\227oH\267Jx\254\066\237\001K\354\332\371̮\213f", ns=0x7ffe45f59a31 "sk", cluster=0x0)
    at src/include/aerospike/as_cluster.h:387
#1  as_command_execute (cluster=0x0, err=0x7ffe45f59ae0, cn=0x7ffe45f598b0, command=0x7ffe45f59840 "\002\003", command_len=72, timeout_ms=20, retry=1, parse_results_fn=0x7f0bc9e4780b <as_command_parse_result>, 
    parse_results_data=0x7ffe45f598d0) at src/main/aerospike/as_command.c:352
#2  0x00007f0bc9e3ef9c in aerospike_key_get (as=0x2c57290, err=0x7ffe45f59ae0, policy=0x7ffe45f59980, key=<optimized out>, rec=0x7ffe45f59968) at src/main/aerospike/aerospike_key.c:91
#3  0x00007f0bc9e131d8 in aerospike_transform_get_record (aerospike_obj_p=0x2d51098, get_rec_key_p=0x7ffe45f59a30, options_p=0x0, error_p=0x7ffe45f59ae0, outer_container_p=0x2d50940, bins_p=0x0)
    at /home/projx/OPENX/vendor/aerospike/aerospike-client-php/src/aerospike/aerospike_transform.c:3465
#4  0x00007f0bc9df2281 in zim_Aerospike_get (ht=2, return_value=0x2d50a30, return_value_ptr=0x0, this_ptr=0x2d4cdb0, return_value_used=1)
```
