### ISSUE TITLE
Client gets stuck if pcntl_fork is used after opening a connection

### ISSUE THREAD

**Issue by crispygoth** [aerospike/aerospike-client-php#86]
I've noticed that a script that uses pcntl_fork to spawn multiple child processes gets stuck if an Aerospike connection is open when the process is forked.

Example script:

```
<?php

$oAS = new Aerospike(['hosts' => [['addr' => '192.168.0.119', 'port' => 3000]]]);
if (!$oAS->isConnected())
{
	trigger_error("unable to connect to Aerospike: {$oAS->errorno()}: {$oAS->error()}",E_USER_ERROR);
}

if ($iPid = pcntl_fork())
{
	$iExitStatus = null;
	$iExitedPID = pcntl_wait($iExitStatus);

	print "[parent] child $iExitedPID exited with status $iExitStatus\n";
}
else
{
	// child
	print "[child] " . getmypid() . " started\n";
	sleep(1);
	print "[child] " . getmypid() . " exiting\n";
	exit(0);
}
```

When I run this, I get the output:

```
[child] 20549 started
[child] 20549 exiting
```

Then it just hangs -- the parent is waiting for the child to exit, but the child is stuck.
Attaching to the child with gdb gives me the following backtrace:

```
pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ff5e0394b0f in cf_queue_pop (q=0x26257b0, buf=buf@entry=0x7fff06868f20, ms_wait=ms_wait@entry=-1) at src/main/citrusleaf/cf_queue.c:339
#2  0x00007ff5e039051d in as_thread_pool_shutdown_threads (pool=pool@entry=0x2621a48, count=16) at src/main/aerospike/as_thread_pool.c:129
#3  0x00007ff5e03909b1 in as_thread_pool_destroy (pool=pool@entry=0x2621a48) at src/main/aerospike/as_thread_pool.c:285
#4  0x00007ff5e038143f in as_cluster_destroy (cluster=0x2621a00) at src/main/aerospike/as_cluster.c:1231
#5  0x00007ff5e036dc77 in aerospike_close (as=0x2621e80, err=0x7fff06869000) at src/main/aerospike/aerospike.c:130
#6  0x00007ff5e03190ab in aerospike_check_close_and_destroy (hashtable_element=0x26219e0) at /home/chrisb/php5-aerospike-3.4.7/src/aerospike/aerospike.c:123
#7  0x00000000006fb0d8 in zend_hash_clean (ht=0x252ef30) at /build/php5-5.6.20+dfsg/Zend/zend_hash.c:584
#8  0x00007ff5e0319501 in aerospike_globals_dtor (globals=0x7ff5e06627c0 <aerospike_globals>) at /home/chrisb/php5-aerospike-3.4.7/src/aerospike/aerospike.c:181
#9  0x00007ff5e0332108 in zm_shutdown_aerospike (type=1, module_number=43) at /home/chrisb/php5-aerospike-3.4.7/src/aerospike/aerospike.c:6297
#10 0x00000000006f43f7 in module_destructor (module=0x2378380) at /build/php5-5.6.20+dfsg/Zend/zend_API.c:2376
#11 0x00000000006f99b6 in i_zend_hash_bucket_delete (p=0x2378320, ht=0xeb6f40 <module_registry>) at /build/php5-5.6.20+dfsg/Zend/zend_hash.c:182
#12 zend_hash_bucket_delete (ht=ht@entry=0xeb6f40 <module_registry>, p=0x2378320) at /build/php5-5.6.20+dfsg/Zend/zend_hash.c:192
#13 0x00000000006fb1b8 in zend_hash_graceful_reverse_destroy (ht=ht@entry=0xeb6f40 <module_registry>) at /build/php5-5.6.20+dfsg/Zend/zend_hash.c:613
#14 0x00000000006f2cdc in zend_destroy_modules () at /build/php5-5.6.20+dfsg/Zend/zend_API.c:1894
#15 0x00000000006ec7bf in zend_shutdown () at /build/php5-5.6.20+dfsg/Zend/zend.c:836
#16 0x0000000000689c4b in php_module_shutdown () at /build/php5-5.6.20+dfsg/main/main.c:2477
#17 0x000000000046282b in main (argc=39999476, argv=0x80) at /build/php5-5.6.20+dfsg/sapi/cli/php_cli.c:1393
```

Looks like it's trying to wait on a thread lock that is no longer valid since the fork.

I've tried adding a call to `$oAS->close()` and/or `unset($oAS);` prior to the fork, but that doesn't seem to help.

**Comment by rbotzer** [comment]
This is similar to [issue 78](https://github.com/aerospike/aerospike-client-python/issues/78) on the Python client side. Please read the comments. Essentially the C client creates threads and connections to the server, so you want to fork before connecting the client.

**Comment by crispygoth** [comment]
Yeah, I found that bug after opening this one. It's a bit inconvenient with the way we're currently using Aerospike, but we can probably work around it for now.

What would be handy is if there was a way to tell the Aerospike client to *completely* close all its connections to the server (and kill all its threads), which we could then do before forking, however I can't see any way to do this?
